### ISSUE TITLE
hi guys its me to point out the obvoius

### ISSUE THREAD

**Issue by Mackery6969** [Test-Engine-Team/Test-Engine-V1---FNF#23]
### Describe your bug here.

uhh game broke as 

### Are you modding a build from source or with Lua?

Source (not reccomended)

### What is your build platform?

Windows

### Checks

- [X] I checked for duplicate issues
- [X] I edited the source code
- [x] I know what causes the crash
- [x] I know how to replicate it

**Comment by MemeHovy** [comment]
mackery I could've tried to help fix it
