### ISSUE TITLE
Remake the Chart Editor and System

### ISSUE THREAD

**Issue by Mackery6969** [Test-Engine-Team/Test-Engine-V1---FNF#26]
### Description

we should remake the chart editor and system (idfk how to do that tbh)

### Checks

- [X] I checked for duplicate suggestions

**Comment by Leather128** [comment]
the chart system???

**Comment by MemeHovy** [comment]
> the chart system???

like the way charts work

**Comment by MemeHovy** [comment]
pretty sure that's what mackery meant

**Comment by Mackery6969** [comment]
yeah
